version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: santa-close-db
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - "3306:3306"

  localstack:
    image: localstack/localstack:0.14.0
    container_name: santa-close-localstack
    ports:
      - "4568:4566"
    environment:
      - SERVICES=s3