graphql:
  packages:
    - "com.santaclose.app"

spring:
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:test;MODE=MYSQL
  #    username: test
  #    password: test

  jpa:
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: update
  #      use-new-id-generator-mappings: true
  #      naming:
  #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
