name: Run Gradle on PRs

on:
  pull_request:
    branches:
      - main

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin

      - name: Run lint check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

      - name: Run test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check files are changed
        run: git diff --exit-code
